name: nurse_ui_lifeec
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  animations: ^2.0.11
  getwidget: ^4.0.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8
  glassmorphism: ^3.0.0
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  provider: ^6.1.2
  logging: ^1.2.0
  logger: ^2.3.0
  font_awesome_flutter: ^10.7.0
  dropdown_search: ^5.0.6
  intl: ^0.19.0
  http: 1.2.2
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/images/personalized_care.png
    - assets/images/meal_management.png
    - assets/images/fill_icon.png
    - assets/images/residents_list.png
    - assets/images/emergency_icon.png
    - assets/images/confirm_icon.png
    - assets/images/cancel_icon.png



  uses-material-design: true